// apps/react-app/src/app/nx-welcome.tsx
export function NxWelcome({ title }: { title: string }) {
    return (
        <>
            <style
                dangerouslySetInnerHTML={{
                    __html: `
    html {
      -webkit-text-size-adjust: 100%;
      font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont,
      'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif,
      'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol',
      'Noto Color Emoji';
      line-height: 1.5;
      tab-size: 4;
      scroll-behavior: smooth;
    }
    body {
      font-family: inherit;
      line-height: inherit;
      margin: 0;
    }
    h1,
    h2,
    p,
    pre {
      margin: 0;
    }
    *,
    ::before,
    ::after {
      box-sizing: border-box;
      border-width: 0;
      border-style: solid;
      border-color: currentColor;
    }
    h1,
    h2 {
      font-size: inherit;
      font-weight: inherit;
    }
    a {
      color: inherit;
      text-decoration: inherit;
    }
    pre {
      font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas,
      'Liberation Mono', 'Courier New', monospace;
    }
    svg {
      display: block;
      vertical-align: middle;
      shape-rendering: auto;
      text-rendering: optimizeLegibility;
    }
    pre {
      background-color: rgba(55, 65, 81, 1);
      border-radius: 0.25rem;
      color: rgba(229, 231, 235, 1);
      font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas,
      'Liberation Mono', 'Courier New', monospace;
      overflow: scroll;
      padding: 0.5rem 0.75rem;
    }

    .shadow {
      box-shadow: 0 0 #0000, 0 0 #0000, 0 10px 15px -3px rgba(0, 0, 0, 0.1),
      0 4px 6px -2px rgba(0, 0, 0, 0.05);
    }
    .rounded {
      border-radius: 1.5rem;
    }
    .wrapper {
      width: 100%;
    }
    .container {
      margin-left: auto;
      margin-right: auto;
      max-width: 768px;
      padding-bottom: 3rem;
      padding-left: 1rem;
      padding-right: 1rem;
      color: rgba(55, 65, 81, 1);
      width: 100%;
    }
    #welcome {
      margin-top: 2.5rem;
    }
    #welcome h1 {
      font-size: 3rem;
      font-weight: 500;
      letter-spacing: -0.025em;
      line-height: 1;
    }
    #welcome span {
      display: block;
      font-size: 1.875rem;
      font-weight: 300;
      line-height: 2.25rem;
      margin-bottom: 0.5rem;
    }
    #hero {
      align-items: center;
      background-color: #8d1616;
      border: none;
      box-sizing: border-box;
      color: rgba(55, 65, 81, 1);
      display: grid;
      grid-template-columns: 1fr;
      margin-top: 3.5rem;
    }
    #hero .text-container {
      color: rgba(255, 255, 255, 1);
      padding: 3rem 2rem;
    }
    #hero .text-container h2 {
      font-size: 1.5rem;
      line-height: 2rem;
      position: relative;
    }
    #hero .text-container h2 svg {
      color: hsla(162, 47%, 50%, 1);
      height: 2rem;
      left: -0.25rem;
      position: absolute;
      top: 0;
      width: 2rem;
    }
    #hero .text-container h2 span {
      margin-left: 2.5rem;
    }
    #hero .text-container a {
      background-color: rgba(255, 255, 255, 1);
      border-radius: 0.75rem;
      color: rgba(55, 65, 81, 1);
      display: inline-block;
      margin-top: 1.5rem;
      padding: 1rem 2rem;
      text-decoration: inherit;
    }
    #hero .logo-container {
      display: none;
      justify-content: center;
      padding-left: 2rem;
      padding-right: 2rem;
    }
    #hero .logo-container svg {
      color: rgba(255, 255, 255, 1);
      width: 66.666667%;
    }
    #middle-content {
      align-items: flex-start;
      display: grid;
      gap: 4rem;
      grid-template-columns: 1fr;
      margin-top: 3.5rem;
    }
    #learning-materials {
      padding: 2.5rem 2rem;
    }
    #learning-materials h2 {
      font-weight: 500;
      font-size: 1.25rem;
      letter-spacing: -0.025em;
      line-height: 1.75rem;
      padding-left: 1rem;
      padding-right: 1rem;
    }
    .list-item-link {
      align-items: center;
      border-radius: 0.75rem;
      display: flex;
      margin-top: 1rem;
      padding: 1rem;
      transition-property: background-color, border-color, color, fill, stroke,
      opacity, box-shadow, transform, filter, backdrop-filter,
      -webkit-backdrop-filter;
      transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
      transition-duration: 150ms;
      width: 100%;
    }
    .list-item-link svg:first-child {
      margin-right: 1rem;
      height: 1.5rem;
      transition-property: background-color, border-color, color, fill, stroke,
      opacity, box-shadow, transform, filter, backdrop-filter,
      -webkit-backdrop-filter;
      transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
      transition-duration: 150ms;
      width: 1.5rem;
    }
    .list-item-link > span {
      flex-grow: 1;
      font-weight: 400;
      transition-property: background-color, border-color, color, fill, stroke,
      opacity, box-shadow, transform, filter, backdrop-filter,
      -webkit-backdrop-filter;
      transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
      transition-duration: 150ms;
    }
    .list-item-link > span > span {
      color: rgba(107, 114, 128, 1);
      display: block;
      flex-grow: 1;
      font-size: 0.75rem;
      font-weight: 300;
      line-height: 1rem;
      transition-property: background-color, border-color, color, fill, stroke,
      opacity, box-shadow, transform, filter, backdrop-filter,
      -webkit-backdrop-filter;
      transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
      transition-duration: 150ms;
    }
    .list-item-link svg:last-child {
      height: 1rem;
      transition-property: all;
      transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
      transition-duration: 150ms;
      width: 1rem;
    }
    .list-item-link:hover {
      color: rgba(255, 255, 255, 1);
      background-color: hsla(162, 47%, 50%, 1);
    }
    .list-item-link:hover > span {}
    .list-item-link:hover > span > span {
      color: rgba(243, 244, 246, 1);
    }
    .list-item-link:hover svg:last-child {
      transform: translateX(0.25rem);
    }
    #other-links {}
    .button-pill {
      padding: 1.5rem 2rem;
      margin-bottom: 2rem;
      transition-duration: 300ms;
      transition-property: background-color, border-color, color, fill, stroke,
      opacity, box-shadow, transform, filter, backdrop-filter,
      -webkit-backdrop-filter;
      transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
      align-items: center;
      display: flex;
    }
    .button-pill svg {
      transition-property: background-color, border-color, color, fill, stroke,
      opacity, box-shadow, transform, filter, backdrop-filter,
      -webkit-backdrop-filter;
      transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
      transition-duration: 150ms;
      flex-shrink: 0;
      width: 3rem;
    }
    .button-pill > span {
      letter-spacing: -0.025em;
      font-weight: 400;
      font-size: 1.125rem;
      line-height: 1.75rem;
      padding-left: 1rem;
      padding-right: 1rem;
    }
    .button-pill span span {
      display: block;
      font-size: 0.875rem;
      font-weight: 300;
      line-height: 1.25rem;
    }
    .button-pill:hover svg,
    .button-pill:hover {
      color: rgba(255, 255, 255, 1) !important;
    }
    #nx-console:hover {
      background-color: rgba(0, 122, 204, 1);
    }
    #nx-console svg {
      color: rgba(0, 122, 204, 1);
    }
    #nx-console-jetbrains {
      margin-top: 2rem;
    }
    #nx-console-jetbrains:hover {
      background-color: rgba(255, 49, 140, 1);
    }
    #nx-console-jetbrains svg {
      color: rgba(255, 49, 140, 1);
    }
    #nx-repo:hover {
      background-color: rgba(24, 23, 23, 1);
    }
    #nx-repo svg {
      color: rgba(24, 23, 23, 1);
    }
    #nx-cloud {
      margin-bottom: 2rem;
      margin-top: 2rem;
      padding: 2.5rem 2rem;
    }
    #nx-cloud > div {
      align-items: center;
      display: flex;
    }
    #nx-cloud > div svg {
      border-radius: 0.375rem;
      flex-shrink: 0;
      width: 3rem;
    }
    #nx-cloud > div h2 {
      font-size: 1.125rem;
      font-weight: 400;
      letter-spacing: -0.025em;
      line-height: 1.75rem;
      padding-left: 1rem;
      padding-right: 1rem;
    }
    #nx-cloud > div h2 span {
      display: block;
      font-size: 0.875rem;
      font-weight: 300;
      line-height: 1.25rem;
    }
    #nx-cloud p {
      font-size: 1rem;
      line-height: 1.5rem;
      margin-top: 1rem;
    }
    #nx-cloud pre {
      margin-top: 1rem;
    }
    #nx-cloud a {
      color: rgba(107, 114, 128, 1);
      display: block;
      font-size: 0.875rem;
      line-height: 1.25rem;
      margin-top: 1.5rem;
      text-align: right;
    }
    #nx-cloud a:hover {
      text-decoration: underline;
    }
    #commands {
      padding: 2.5rem 2rem;
      margin-top: 3.5rem;
    }
    #commands h2 {
      font-size: 1.25rem;
      font-weight: 400;
      letter-spacing: -0.025em;
      line-height: 1.75rem;
      padding-left: 1rem;
      padding-right: 1rem;
    }
    #commands p {
      font-size: 1rem;
      font-weight: 300;
      line-height: 1.5rem;
      margin-top: 1rem;
      padding-left: 1rem;
      padding-right: 1rem;
    }
    details {
      align-items: center;
      display: flex;
      margin-top: 1rem;
      padding-left: 1rem;
      padding-right: 1rem;
      width: 100%;
    }
    details pre > span {
      color: rgba(181, 181, 181, 1);
      display: block;
    }
    summary {
      border-radius: 0.5rem;
      display: flex;
      font-weight: 400;
      padding: 0.5rem;
      cursor: pointer;
      transition-property: background-color, border-color, color, fill, stroke,
      opacity, box-shadow, transform, filter, backdrop-filter,
      -webkit-backdrop-filter;
      transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
      transition-duration: 150ms;
    }
    summary:hover {
      background-color: rgba(243, 244, 246, 1);
    }
    summary svg {
      height: 1.5rem;
      margin-right: 1rem;
      width: 1.5rem;
    }
    #love {
      color: rgba(107, 114, 128, 1);
      font-size: 0.875rem;
      line-height: 1.25rem;
      margin-top: 3.5rem;
      opacity: 0.6;
      text-align: center;
    }
    #love svg {
      color: rgba(252, 165, 165, 1);
      width: 1.25rem;
      height: 1.25rem;
      display: inline;
      margin-top: -0.25rem;
    }
    @media screen and (min-width: 768px) {
      #hero {
        grid-template-columns: repeat(2, minmax(0, 1fr));
      }
      #hero .logo-container {
        display: flex;
      }
      #middle-content {
        grid-template-columns: repeat(2, minmax(0, 1fr));
      }
    }
          `,
                }}
            />
            <div className="wrapper">
                <div className="container">
                    <div id="welcome">
                        <h1>
                            <span> Hello from React, </span>
                            Welcome &lt;{title}&gt; 👋
                        </h1>
                    </div>

                    <div id="hero" className="rounded">
                        <div className="text-container">
                            <h2>
                                <svg
                                    fill="none"
                                    stroke="currentColor"
                                    viewBox="0 0 24 24"
                                    xmlns="http://www.w3.org/2000/svg"
                                >
                                    <path
                                        strokeLinecap="round"
                                        strokeLinejoin="round"
                                        strokeWidth="2"
                                        d="M9 12l2 2 4-4M7.835 4.697a3.42 3.42 0 001.946-.806 3.42 3.42 0 014.438 0 3.42 3.42 0 001.946.806 3.42 3.42 0 013.138 3.138 3.42 3.42 0 00.806 1.946 3.42 3.42 0 010 4.438 3.42 3.42 0 00-.806 1.946 3.42 3.42 0 01-3.138 3.138 3.42 3.42 0 00-1.946.806 3.42 3.42 0 01-4.438 0 3.42 3.42 0 00-1.946-.806 3.42 3.42 0 01-3.138-3.138 3.42 3.42 0 00-.806-1.946 3.42 3.42 0 010-4.438 3.42 3.42 0 00.806-1.946 3.42 3.42 0 013.138-3.138z"
                                    />
                                </svg>
                                <span>We are using React 18</span>
                            </h2>
                            <a href="#commands">Module Federation Enabled</a>
                        </div>
                        <div className="logo-container">
                            <img
                                alt="File:React-icon.svg"
                                src="//upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/512px-React-icon.svg.png"
                                decoding="async"
                                width="128"
                                height="114"
                                srcSet="//upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/768px-React-icon.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/1024px-React-icon.svg.png 2x"
                            />
                        </div>
                    </div>
                </div>
            </div>
        </>
    );
}

export default NxWelcome;

// apps/creativeset-list/src/app/remote-entry/nx-welcome.component.ts
import { Component, WritableSignal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { CreativesetListService } from '../creativeset-list.service';

@Component({
    selector: 'mfe-demo-nx-welcome',
    standalone: true,
    imports: [CommonModule],
    template: `
        <style>
            html {
                -webkit-text-size-adjust: 100%;
                font-family: ui-sans-serif, system-ui, -apple-system,
                    BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue',
                    Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji',
                    'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
                line-height: 1.5;
                tab-size: 4;
                scroll-behavior: smooth;
            }
            body {
                font-family: inherit;
                line-height: inherit;
                margin: 0;
            }
            h1,
            h2,
            p,
            pre {
                margin: 0;
            }
            *,
            ::before,
            ::after {
                box-sizing: border-box;
                border-width: 0;
                border-style: solid;
                border-color: currentColor;
            }
            h1,
            h2 {
                font-size: inherit;
                font-weight: inherit;
            }
            a {
                color: inherit;
                text-decoration: inherit;
            }
            pre {
                font-family: ui-monospace, SFMono-Regular, Menlo, Monaco,
                    Consolas, 'Liberation Mono', 'Courier New', monospace;
            }
            svg {
                display: block;
                vertical-align: middle;
            }
            svg {
                shape-rendering: auto;
                text-rendering: optimizeLegibility;
            }
            pre {
                background-color: rgba(55, 65, 81, 1);
                border-radius: 0.25rem;
                color: rgba(229, 231, 235, 1);
                font-family: ui-monospace, SFMono-Regular, Menlo, Monaco,
                    Consolas, 'Liberation Mono', 'Courier New', monospace;
                overflow: scroll;
                padding: 0.5rem 0.75rem;
            }
            .shadow {
                box-shadow: 0 0 #0000, 0 0 #0000,
                    0 10px 15px -3px rgba(0, 0, 0, 0.1),
                    0 4px 6px -2px rgba(0, 0, 0, 0.05);
            }
            .rounded {
                border-radius: 1.5rem;
            }
            .wrapper {
                width: 100%;
            }
            .container {
                margin-left: auto;
                margin-right: auto;
                max-width: 768px;
                padding-bottom: 3rem;
                padding-left: 1rem;
                padding-right: 1rem;
                color: rgba(55, 65, 81, 1);
                width: 100%;
            }
            #welcome {
                margin-top: 2.5rem;
            }
            #welcome h1 {
                font-size: 3rem;
                font-weight: 500;
                letter-spacing: -0.025em;
                line-height: 1;
            }
            #welcome span {
                display: block;
                font-size: 1.875rem;
                font-weight: 300;
                line-height: 2.25rem;
                margin-bottom: 0.5rem;
            }
            #hero {
                align-items: center;
                background-color: hsla(214, 62%, 21%, 1);
                border: none;
                box-sizing: border-box;
                color: rgba(55, 65, 81, 1);
                display: grid;
                grid-template-columns: 1fr;
                margin-top: 3.5rem;
            }
            #hero .text-container {
                color: rgba(255, 255, 255, 1);
                padding: 3rem 2rem;
            }
            #hero .text-container h2 {
                font-size: 1.5rem;
                line-height: 2rem;
                position: relative;
            }
            #hero .text-container h2 svg {
                color: hsla(162, 47%, 50%, 1);
                height: 2rem;
                left: -0.25rem;
                position: absolute;
                top: 0;
                width: 2rem;
            }
            #hero .text-container h2 span {
                margin-left: 2.5rem;
            }
            #hero .text-container a {
                background-color: rgba(255, 255, 255, 1);
                border-radius: 0.75rem;
                color: rgba(55, 65, 81, 1);
                display: inline-block;
                margin-top: 1.5rem;
                padding: 1rem 2rem;
                text-decoration: inherit;
            }
            #hero .logo-container {
                display: none;
                justify-content: center;
                padding-left: 2rem;
                padding-right: 2rem;
            }
            #hero .logo-container svg {
                color: rgba(255, 255, 255, 1);
                width: 66.666667%;
            }
            #middle-content {
                align-items: flex-start;
                display: grid;
                gap: 4rem;
                grid-template-columns: 1fr;
                margin-top: 3.5rem;
            }
            #learning-materials {
                padding: 2.5rem 2rem;
            }
            #learning-materials h2 {
                font-weight: 500;
                font-size: 1.25rem;
                letter-spacing: -0.025em;
                line-height: 1.75rem;
                padding-left: 1rem;
                padding-right: 1rem;
            }
            .list-item-link {
                align-items: center;
                border-radius: 0.75rem;
                display: flex;
                margin-top: 1rem;
                padding: 1rem;
                transition-property: background-color, border-color, color, fill,
                    stroke, opacity, box-shadow, transform, filter,
                    backdrop-filter, -webkit-backdrop-filter;
                transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
                transition-duration: 150ms;
                width: 100%;
            }
            .list-item-link svg:first-child {
                margin-right: 1rem;
                height: 1.5rem;
                transition-property: background-color, border-color, color, fill,
                    stroke, opacity, box-shadow, transform, filter,
                    backdrop-filter, -webkit-backdrop-filter;
                transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
                transition-duration: 150ms;
                width: 1.5rem;
            }
            .list-item-link > span {
                flex-grow: 1;
                font-weight: 400;
                transition-property: background-color, border-color, color, fill,
                    stroke, opacity, box-shadow, transform, filter,
                    backdrop-filter, -webkit-backdrop-filter;
                transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
                transition-duration: 150ms;
            }
            .list-item-link > span > span {
                color: rgba(107, 114, 128, 1);
                display: block;
                flex-grow: 1;
                font-size: 0.75rem;
                font-weight: 300;
                line-height: 1rem;
                transition-property: background-color, border-color, color, fill,
                    stroke, opacity, box-shadow, transform, filter,
                    backdrop-filter, -webkit-backdrop-filter;
                transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
                transition-duration: 150ms;
            }
            .list-item-link svg:last-child {
                height: 1rem;
                transition-property: all;
                transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
                transition-duration: 150ms;
                width: 1rem;
            }
            .list-item-link:hover {
                color: rgba(255, 255, 255, 1);
                background-color: hsla(162, 47%, 50%, 1);
            }
            .list-item-link:hover > span {
            }
            .list-item-link:hover > span > span {
                color: rgba(243, 244, 246, 1);
            }
            .list-item-link:hover svg:last-child {
                transform: translateX(0.25rem);
            }
            #other-links {
            }
            .button-pill {
                padding: 1.5rem 2rem;
                margin-bottom: 2rem;
                transition-duration: 300ms;
                transition-property: background-color, border-color, color, fill,
                    stroke, opacity, box-shadow, transform, filter,
                    backdrop-filter, -webkit-backdrop-filter;
                transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
                align-items: center;
                display: flex;
            }
            .button-pill svg {
                transition-property: background-color, border-color, color, fill,
                    stroke, opacity, box-shadow, transform, filter,
                    backdrop-filter, -webkit-backdrop-filter;
                transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
                transition-duration: 150ms;
                flex-shrink: 0;
                width: 3rem;
            }
            .button-pill > span {
                letter-spacing: -0.025em;
                font-weight: 400;
                font-size: 1.125rem;
                line-height: 1.75rem;
                padding-left: 1rem;
                padding-right: 1rem;
            }
            .button-pill span span {
                display: block;
                font-size: 0.875rem;
                font-weight: 300;
                line-height: 1.25rem;
            }
            .button-pill:hover svg,
            .button-pill:hover {
                color: rgba(255, 255, 255, 1) !important;
            }
            .nx-console:hover {
                background-color: rgba(0, 122, 204, 1);
            }
            .nx-console svg {
                color: rgba(0, 122, 204, 1);
            }
            .nx-console-jetbrains {
                margin-top: 2rem;
            }
            .nx-console-jetbrains:hover {
                background-color: rgba(255, 49, 140, 1);
            }
            .nx-console-jetbrains svg {
                color: rgba(255, 49, 140, 1);
            }
            #nx-repo:hover {
                background-color: rgba(24, 23, 23, 1);
            }
            #nx-repo svg {
                color: rgba(24, 23, 23, 1);
            }
            #nx-cloud {
                margin-bottom: 2rem;
                margin-top: 2rem;
                padding: 2.5rem 2rem;
            }
            #nx-cloud > div {
                align-items: center;
                display: flex;
            }
            #nx-cloud > div svg {
                border-radius: 0.375rem;
                flex-shrink: 0;
                width: 3rem;
            }
            #nx-cloud > div h2 {
                font-size: 1.125rem;
                font-weight: 400;
                letter-spacing: -0.025em;
                line-height: 1.75rem;
                padding-left: 1rem;
                padding-right: 1rem;
            }
            #nx-cloud > div h2 span {
                display: block;
                font-size: 0.875rem;
                font-weight: 300;
                line-height: 1.25rem;
            }
            #nx-cloud p {
                font-size: 1rem;
                line-height: 1.5rem;
                margin-top: 1rem;
            }
            #nx-cloud pre {
                margin-top: 1rem;
            }
            #nx-cloud a {
                color: rgba(107, 114, 128, 1);
                display: block;
                font-size: 0.875rem;
                line-height: 1.25rem;
                margin-top: 1.5rem;
                text-align: right;
            }
            #nx-cloud a:hover {
                text-decoration: underline;
            }
            #commands {
                padding: 2.5rem 2rem;
                margin-top: 3.5rem;
            }
            #commands h2 {
                font-size: 1.25rem;
                font-weight: 400;
                letter-spacing: -0.025em;
                line-height: 1.75rem;
                padding-left: 1rem;
                padding-right: 1rem;
            }
            #commands p {
                font-size: 1rem;
                font-weight: 300;
                line-height: 1.5rem;
                margin-top: 1rem;
                padding-left: 1rem;
                padding-right: 1rem;
            }
            details {
                align-items: center;
                display: flex;
                margin-top: 1rem;
                padding-left: 1rem;
                padding-right: 1rem;
                width: 100%;
            }
            details pre > span {
                color: rgba(181, 181, 181, 1);
            }
            summary {
                border-radius: 0.5rem;
                display: flex;
                font-weight: 400;
                padding: 0.5rem;
                cursor: pointer;
                transition-property: background-color, border-color, color, fill,
                    stroke, opacity, box-shadow, transform, filter,
                    backdrop-filter, -webkit-backdrop-filter;
                transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
                transition-duration: 150ms;
            }
            summary:hover {
                background-color: rgba(243, 244, 246, 1);
            }
            summary svg {
                height: 1.5rem;
                margin-right: 1rem;
                width: 1.5rem;
            }
            #love {
                color: rgba(107, 114, 128, 1);
                font-size: 0.875rem;
                line-height: 1.25rem;
                margin-top: 3.5rem;
                opacity: 0.6;
                text-align: center;
            }
            #love svg {
                color: rgba(252, 165, 165, 1);
                width: 1.25rem;
                height: 1.25rem;
                display: inline;
                margin-top: -0.25rem;
            }
            @media screen and (min-width: 768px) {
                #hero {
                    grid-template-columns: repeat(2, minmax(0, 1fr));
                }
                #hero .logo-container {
                    display: flex;
                }
                #middle-content {
                    grid-template-columns: repeat(2, minmax(0, 1fr));
                }
            }
        </style>
        <div class="wrapper">
            <div class="container">
                <!--  WELCOME  -->
                <div id="welcome">
                    <h1>
                        <span> Hello from Angular, </span>
                        Welcome &lt;creativeset-list&gt; 👋
                    </h1>
                </div>
                <!--  HERO  -->
                <div id="hero" class="rounded" [style.background]="color()">
                    <div class="text-container">
                        <h2>
                            <svg
                                fill="none"
                                stroke="currentColor"
                                viewBox="0 0 24 24"
                                xmlns="http://www.w3.org/2000/svg"
                            >
                                <path
                                    stroke-linecap="round"
                                    stroke-linejoin="round"
                                    stroke-width="2"
                                    d="M9 12l2 2 4-4M7.835 4.697a3.42 3.42 0 001.946-.806 3.42 3.42 0 014.438 0 3.42 3.42 0 001.946.806 3.42 3.42 0 013.138 3.138 3.42 3.42 0 00.806 1.946 3.42 3.42 0 010 4.438 3.42 3.42 0 00-.806 1.946 3.42 3.42 0 01-3.138 3.138 3.42 3.42 0 00-1.946.806 3.42 3.42 0 01-4.438 0 3.42 3.42 0 00-1.946-.806 3.42 3.42 0 01-3.138-3.138 3.42 3.42 0 00-.806-1.946 3.42 3.42 0 010-4.438 3.42 3.42 0 00.806-1.946 3.42 3.42 0 013.138-3.138z"
                                />
                            </svg>
                            <span>Running Angular 17</span>
                        </h2>
                        <a href="#commands">Module Federated</a>
                    </div>
                    <div class="logo-container">
                        <svg
                            fill="currentColor"
                            role="img"
                            viewBox="0 0 24 24"
                            xmlns="http://www.w3.org/2000/svg"
                        >
                            <path
                                d="M11.987 14.138l-3.132 4.923-5.193-8.427-.012 8.822H0V4.544h3.691l5.247 8.833.005-3.998 3.044 4.759zm.601-5.761c.024-.048 0-3.784.008-3.833h-3.65c.002.059-.005 3.776-.003 3.833h3.645zm5.634 4.134a2.061 2.061 0 0 0-1.969 1.336 1.963 1.963 0 0 1 2.343-.739c.396.161.917.422 1.33.283a2.1 2.1 0 0 0-1.704-.88zm3.39 1.061c-.375-.13-.8-.277-1.109-.681-.06-.08-.116-.17-.176-.265a2.143 2.143 0 0 0-.533-.642c-.294-.216-.68-.322-1.18-.322a2.482 2.482 0 0 0-2.294 1.536 2.325 2.325 0 0 1 4.002.388.75.75 0 0 0 .836.334c.493-.105.46.36 1.203.518v-.133c-.003-.446-.246-.55-.75-.733zm2.024 1.266a.723.723 0 0 0 .347-.638c-.01-2.957-2.41-5.487-5.37-5.487a5.364 5.364 0 0 0-4.487 2.418c-.01-.026-1.522-2.39-1.538-2.418H8.943l3.463 5.423-3.379 5.32h3.54l1.54-2.366 1.568 2.366h3.541l-3.21-5.052a.7.7 0 0 1-.084-.32 2.69 2.69 0 0 1 2.69-2.691h.001c1.488 0 1.736.89 2.057 1.308.634.826 1.9.464 1.9 1.541a.707.707 0 0 0 1.066.596zm.35.133c-.173.372-.56.338-.755.639-.176.271.114.412.114.412s.337.156.538-.311c.104-.231.14-.488.103-.74z"
                            />
                        </svg>
                    </div>
                </div>
            </div>
        </div>
    `,
    styles: [],
})
export class NxWelcomeComponent {
    color: WritableSignal<string>;

    constructor(private creativesetListService: CreativesetListService) {
        this.color = this.creativesetListService.color;
    }
}
